### ISSUE TITLE
Difficulty labels?

### ISSUE THREAD

**Issue by cmckni3** [yoshuawuyts/github-standard-labels#6]
I think difficulty labels would be nice

```
easy green
medium yellow
hard red/orange
```

**Comment by yoshuawuyts** [comment]
Haha, I don't know how useful those would be. Difficulty is hard to estimate, as what might be hard for one person might be trivial for another. E.g. I don't know how to design an SVG, and a designer might not know how to write protocols. Depending on someone's skill set, a task might be easy or hard — making a label to estimate something that is as subjective as difficulty probably shouldn't be part of standard-labels.

Does this make sense?

**Comment by cmckni3** [comment]
I suppose. I guess I was getting more at how much effort something might take even for someone experienced. Some projects uses `easy`, `medium`, `hard` and some use sizes, `small`, `medium`, `large`, `xlarge`. Think [story estimates](https://www.pivotaltracker.com/help/articles/estimating_stories/)
